apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    uid: postgres_ds
    isDefault: true
    access: proxy
    url: postgres:5432
    user: trafficuser
    secureJsonData:
      password: trafficpass
    jsonData:
      postgresVersion: 1600
      sslmode: disable
      database: trafficdb
      timescaledb: false
      timeColumn: read_time
      timezone: UTC
    editable: true
