apiVersion: 1

datasources:
  - name: PostgreSQL-Traffic
    uid: DS_POSTGRESQL-TRAFFIC
    type: postgres
    access: proxy
    url: postgres:5432
    user: trafficuser
    password: trafficpass
    database: trafficdb
    isDefault: true
    jsonData:
      sslmode: disable
